### ISSUE TITLE
not working at all for me...dunno why, tho...

### ISSUE THREAD

**Issue by rchrdnsh** [mattjennings/mdsvex-relative-images#4]
Hi Matt,

Thank you for putting time into this, as it is a pain point for me as well. I have been trying to use it as the installation and usage instructions indicate, but it doesn't seem to work for me in any case.

Tried it both ways:

```markdown
![The cave paintings of El Castillo.](./el-castillo-cave-painting.jpg)
```

or
```html
<img
  src='./el-castillo-cave-painting.jpg'
  alt='The cave paintings of El Castillo.'
/>
```
...and no dice either way. One thing I am doing is I have a separate `content` folder that I am storing the content in, rather than this stuff living in the `routes` folder...dunno if maybe that has an effect on the plugin or not. Otherwise it's a `+content.md` file living next to the assets in the same folder where the route name is sourced.

**Comment by mattjennings** [comment]
Hm, it shouldn’t matter where the post is, but it’s hard to help without seeing a reproduction. 

I use this plugin for my svelte kit sites, so you might want to reference [this](https://github.com/mattjennings/sveltekit-blog-template) and see how it compares to how you’ve set yours up. Otherwise, if you can provide a reproduction for me I can take a further look into it.

**Comment by rchrdnsh** [comment]
ok, good to know placement does not matter :-) I'll take a look at your code and also see if I can make some kind of minrep...this is a very large and complex project...not sure how to go about it, but hopefully I can find a way....

**Comment by mattjennings** [comment]
Closing this for now, if you can provide a repro I will re-open it.
